#!/bin/python3

from datetime import datetime

def time_delta(t1, t2):
    time_format = "%a %d %b %Y %H:%M:%S %z"
    
    
    dt1 = datetime.strptime(t1, time_format)
    dt2 = datetime.strptime(t2, time_format)
    
    
    delta = abs((dt1 - dt2).total_seconds())
    
    return str(int(delta))
